In [1]:
from PIL import Image
import numpy as np
from data.pix2pix_dataset import Pix2pixDataset
from data.image_folder import make_dataset
from options.test_options import TestOptions
from data.base_dataset import get_params, get_transform

In [2]:
a = np.ones((256, 256))

In [4]:
a[:2] = a[:2] * 50

In [12]:
for i, val in enumerate(np.unique(a)):
    a[a==val] = i
#     print(np.where(a == val, a, i))

In [15]:
np.copy(a)

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [24]:
opts = TestOptions()
opts.preprocess_mode = 'scale_width_and_crop'
opts.load_size = 1024
opts.crop_size = 512
opts.isTrain = False
opts.label_nc = 182

In [25]:
label_path = 'datasets/coco_stuff/train_label/000000017914.png'

label = Image.open(label_path)
params = get_params(opts, label.size)
transform_label = get_transform(opts, params, method=Image.NEAREST, normalize=False)
label_tensor = transform_label(label) * 255.0
label_tensor[label_tensor == 255] = opts.label_nc  # 'unknown' is opt.label_nc

In [26]:
label_tensor.shape

torch.Size([1, 512, 512])

In [27]:
label_tensor

tensor([[[182., 182., 182.,  ..., 182., 182., 182.],
         [182., 182., 182.,  ..., 182., 182., 182.],
         [182., 182., 182.,  ..., 182., 182., 182.],
         ...,
         [  0.,   0.,   0.,  ...,  16.,  16.,  16.],
         [  0.,   0.,   0.,  ...,  16.,  16.,  16.],
         [  0.,   0.,   0.,  ...,  16.,  16.,  16.]]])

In [33]:
np.asarray(label).shape

(375, 500)

In [38]:
label_tensor.reshape((1, 1, 512, 512)).shape

torch.Size([1, 1, 512, 512])